### ISSUE TITLE
Shadow of the Erdtree Data

### ISSUE THREAD

**Issue by Camburgaler** [vodofrede/erdtree#1]
With the release of the DLC, there is a bounty of new equipment data to be collected and inserted into the repo. Are there currently any plans to start this work soon? Just wondering, no rush.

P.S.
Thanks for making these tools. Very helpful!

**Comment by vodofrede** [comment]
Thanks for the nice feedback =). 
Unfortunately, I will not be updating the equipment data for some time as I do not have the time nor will to do so at the moment. 

However, the original scripts still exists, and could be used by someone with the DLC to extract the new weapons:
https://git.palmoe.dk/vodofrede/erdtree-utils 
The hardcoded table column names have been changed, which is why the dataset was not updated beyond the original version, so they have to be pinpointed again, probably by exporting the tables to a spreadsheet format for inspection.
